{% set name = "openmm-hip" %}
{% set version = "8.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/StreamHPC/openmm-hip/archive/refs/tags/{{ version }}.tar.gz
    sha256: 6fc3547f39b8449773edff32170d842af1f5f60b8f2378c74ebc2261a50d9c14
    folder: openmm-hip
  - url: https://github.com/openmm/openmm/archive/refs/tags/{{ version }}.tar.gz
    sha256: 347ad9f04dd88a673f7871127d9f23a75caf2c1a460a3f21f3328a24dc6547d0
    folder: openmm


build:
  number: 0
  skip: True  # [not linux]
  rpaths:
    - lib
    - lib/plugins

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - hip-devel
    - hipcc
    - hipfft
    - rocfft
    - rocm-cmake
    - rocm-device-libs
    - openmm {{ version }}
  run:
    - {{ pin_compatible("hipfft") }}
    - {{ pin_compatible("openmm", max_pin="x.x.x") }}

test:
  imports:
    - openmm

about:
  home: https://openmm.org
  summary: Openmm-hip plugin
  description: |
    This plugin adds HIP platform that allows to run OpenMM on CDNA and RDNA AMD GPUs on AMD ROCm open software platform.
  license: LGPL-3.0-or-later AND MIT
  license_file:
    - openmm-hip/licenses/MIT.txt
    - openmm-hip/licenses/GPL.txt
    - openmm-hip/licenses/LGPL.txt
    - openmm-hip/licenses/MIT-VkFFT.txt
  dev_url: https://github.com/StreamHPC/openmm-hip

extra:
  recipe-maintainers:
    - peastman
    - mikemhenry
    - zklaus
    - hmacdope
    - ex-rzr
