{% set name = "openmm-hip" %}
{% set version = "8.2.0beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/openmm/openmm.git
  git_rev: "fed44c5"

build:
  number: 0
  skip: True  # [not linux]
  rpaths:
    - lib
    - lib/plugins

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - hip-devel
    - hipcc
    - rocm-cmake
    - rocm-device-libs
    - openmm
    #- openmm {{ version }}
  run:
    - {{ pin_compatible("openmm", max_pin="x.x.x") }}

about:
  home: https://openmm.org
  summary: Openmm-HIP plugin
  description: |
    This plugin adds HIP platform that allows to run OpenMM on CDNA and RDNA AMD GPUs on AMD ROCm open software platform.
  license: LGPL-3.0-or-later AND MIT
  license_file:
    - openmm-hip/licenses/MIT.txt
    - openmm-hip/licenses/GPL.txt
    - openmm-hip/licenses/LGPL.txt
    - openmm-hip/licenses/MIT-VkFFT.txt
  dev_url: https://github.com/openmm/openmm

extra:
  recipe-maintainers:
    - peastman
    - mikemhenry
    - zklaus
    - hmacdope
    - ex-rzr
